#![cfg(feature = "testing")]

use resina_model::PhysicalVector;
use resina_resolver::resolve_surface_paint_source;
use resina_slint_runtime::prepare_surface_paint;
use slint::platform::software_renderer::{MinimalSoftwareWindow, RepaintBufferType};
use slint::platform::{Platform, PlatformError, WindowAdapter, WindowEvent};
use slint::{ComponentHandle, PhysicalSize};
use std::rc::Rc;

slint::slint! {
    export struct PaintData {
        image: image,
        origin-x: length,
        origin-y: length,
        extent-x: length,
        extent-y: length,
    }
    export component PaintWindow inherits Window {
        width: 320px;
        height: 160px;
        in property <PaintData> paint;
        in property <color> surrounding;
        background: surrounding;
        Image {
            source: root.paint.image;
            x: root.paint.origin-x;
            y: root.paint.origin-y;
            width: root.paint.extent-x;
            height: root.paint.extent-y;
            image-fit: fill;
            image-rendering: pixelated;
            accessible-role: none;
        }
    }
}

struct SoftwarePlatform(Rc<MinimalSoftwareWindow>);

impl Platform for SoftwarePlatform {
    fn create_window_adapter(&self) -> Result<Rc<dyn WindowAdapter>, PlatformError> {
        Ok(self.0.clone())
    }
}

#[test]
fn compiled_publication_replaces_material_focus_placement_and_scale() {
    let catalog: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(std::env::var("RESINA_SCENES").expect(
            "RESINA_SCENES must name the catalog generated by tools/material_scenarios.py",
        ))
        .unwrap(),
    )
    .unwrap();
    let scenes: Vec<_> = catalog["scenarios"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|scene| scene["kind"] == "surfacePaint")
        .collect();
    assert_eq!(scenes.len(), 16);
    let names: std::collections::BTreeSet<_> = scenes
        .iter()
        .map(|scene| scene["name"].as_str().unwrap())
        .collect();
    assert_eq!(names.len(), 16, "material scene names must be distinct");
    let window = MinimalSoftwareWindow::new(RepaintBufferType::NewBuffer);
    slint::platform::set_platform(Box::new(SoftwarePlatform(window.clone()))).unwrap();
    let ui = PaintWindow::new().unwrap();
    let mut frames = 0;
    for scale in [0.5_f32, 1.0, 1.25, 2.0, 1.3] {
        window.dispatch_event(WindowEvent::ScaleFactorChanged {
            scale_factor: scale,
        });
        let size = PhysicalSize::new(
            (320.0 * scale).round() as u32,
            (160.0 * scale).round() as u32,
        );
        window.set_size(size);
        assert_eq!(ui.window().scale_factor(), scale);
        for (index, scene) in scenes.iter().enumerate() {
            let placement = if index % 2 == 0 {
                PhysicalVector { x: 44.3, y: 26.1 }
            } else {
                PhysicalVector { x: 54.1, y: 33.7 }
            };
            let request = scene["request"].to_string();
            let ir = resolve_surface_paint_source(&request).unwrap();
            let snapshot = std::thread::spawn(move || {
                let ir = resolve_surface_paint_source(&request).unwrap();
                prepare_surface_paint(&ir, placement, scale, 4).unwrap()
            })
            .join()
            .unwrap()
            .into_snapshot();
            assert_eq!(snapshot.device_scale, ui.window().scale_factor());
            let surrounding = &scene["request"]["surroundingColor"];
            assert_eq!(surrounding["colorSpace"], "srgb");
            assert_eq!(surrounding["alpha"].as_f64(), Some(1.0));
            let channels = surrounding["components"].as_array().unwrap();
            assert_eq!(channels.len(), 3);
            let background: [u8; 3] =
                std::array::from_fn(|i| (channels[i].as_f64().unwrap() * 255.0).round() as u8);
            ui.set_surrounding(slint::Color::from_rgb_u8(
                background[0],
                background[1],
                background[2],
            ));
            ui.set_paint(PaintData {
                image: snapshot.image,
                origin_x: snapshot.origin[0],
                origin_y: snapshot.origin[1],
                extent_x: snapshot.logical_size[0],
                extent_y: snapshot.logical_size[1],
            });
            if frames == 0 {
                ui.show().unwrap();
            }
            let captured = ui.window().take_snapshot().unwrap();
            assert_eq!(captured.width(), size.width);
            assert_eq!(captured.height(), size.height);
            let bounds = if let Some(focus) = ir.focus() {
                let outer = focus.geometry().outer();
                let mut bounds = outer.contour().bounds().unwrap();
                bounds.x += outer.offset().x;
                bounds.y += outer.offset().y;
                bounds
            } else {
                ir.body().geometry().silhouette().bounds().unwrap()
            };
            let scale = f64::from(scale);
            let left = ((bounds.x + placement.x) * scale).floor() as u32;
            let top = ((bounds.y + placement.y) * scale).floor() as u32;
            let width = ((bounds.x + bounds.width + placement.x) * scale).ceil() as u32 - left;
            let height = ((bounds.y + bounds.height + placement.y) * scale).ceil() as u32 - top;
            let paint = resina_raster::render_surface_paint(
                &ir,
                resina_raster::Viewport {
                    origin: PhysicalVector {
                        x: f64::from(left) / scale - placement.x,
                        y: f64::from(top) / scale - placement.y,
                    },
                    width,
                    height,
                    pixels_per_unit: scale,
                },
                4,
            )
            .unwrap();
            for y in 0..size.height {
                for x in 0..size.width {
                    let mut expected = background;
                    if x >= left && y >= top && x - left < width && y - top < height {
                        let offset = (((y - top) * width + x - left) * 4) as usize;
                        let rgba = &paint.rgba()[offset..offset + 4];
                        for i in 0..3 {
                            expected[i] = ((u32::from(rgba[i]) * u32::from(rgba[3])
                                + u32::from(background[i]) * (255 - u32::from(rgba[3]))
                                + 127)
                                / 255) as u8;
                        }
                    }
                    let offset = ((y * size.width + x) * 4) as usize;
                    let actual = &captured.as_bytes()[offset..offset + 4];
                    assert_eq!(actual[3], 255, "frame {frames}, ({x}, {y}) alpha");
                    for channel in 0..3 {
                        assert!(
                            expected[channel].abs_diff(actual[channel]) <= 1,
                            "frame {frames}, {} scale {scale}, ({x}, {y}): expected {expected:?}, actual {actual:?}",
                            scene["name"]
                        );
                    }
                }
            }
            if let Some(directory) = std::env::var_os("RESINA_CAPTURE_DIR") {
                use std::io::Write;
                let path = std::path::Path::new(&directory).join(format!(
                    "frame-{frames}-{}x{}.rgba",
                    size.width, size.height
                ));
                std::fs::File::options()
                    .write(true)
                    .create_new(true)
                    .open(path)
                    .unwrap()
                    .write_all(captured.as_bytes())
                    .unwrap();
            }
            frames += 1;
        }
    }
    assert_eq!(frames, 80);
    ui.hide().unwrap();
}
